#!/usr/bin/env python3

# This script takes a cluster size output file from clstr_size_stat.pl and creates a scatter plot of the number of clusters versus cluster size.  The scatterplot is saved as a pdf file.

# Usage: plot_cluster_size.py <cluster size file>
# <cluster size file> = path to the cluster size file.  This file is generated by clstr_size_stat.pl

# python imports
import sys

# Set up the backend to pyplot
import matplotlib
matplotlib.use('pdf')

import matplotlib.pyplot as plt
import numpy as np


# Grab the command line argument
cluster_size_file = sys.argv[1]

# Load the data with Numpy's loadtxt function
# The cluster size input file contains a header row and is delimited by tabs.
# The first column is the size of the cluster
# The second column is the number of clusters with that size
# The third column is the total number of sequences in all the clusters of that size
data = np.loadtxt(cluster_size_file, skiprows=1, delimiter="\t")
cluster_size = data[:,0]
num_clusters = data[:,1]

# Create the scaatterplot
plt.figure()
plt.scatter(cluster_size, num_clusters)

# Annotate the plot
plt.title("Cluster size distribution")
plt.xlabel("Cluster size")
plt.ylabel("Number of clusters")

# Save the plot
# Save the figure as <cluster_size_file>.pdf.  For example, if cluster_size_file = "file", call the figure "file.pdf"
figure_name = cluster_size_file + ".pdf"
plt.savefig(figure_name)
